Grades ui
thecourseforum/theCourseForum2 pull request #165
Opened 2020-10-18 04:10 UTC by ArjunK01

# What I did
Just showing progress on grades ui 
Added chart.js and did some bootstrap formatting

## Issues addressed

# Screenshots
![Screen Shot 2020-10-18 at 12 09 30 AM](https://user-images.githubusercontent.com/55065464/96358535-3600cd00-10d6-11eb-9514-92b7c10ccf7d.png)

2020-10-18 05:07 UTC, j-alicia-long reviewed
@ArjunK01 @alex-shen1 Y'all consulted and decided to import the Chart.js bundle in order to avoid using npm, right? 

We should consult someone to see if it's better to use npm or do this...Jihoon's PR (#153 ) is currently blocked for the same reason.
@brian-yu @bradknaysi @saikonuri ?

2020-11-12 01:56 UTC, Bartleby2718 requested changes
There are so many duplicate files that it is hard to identify which changes are actual changes. Please let me know when you're done deleting them.

2020-11-12 01:56 UTC, Bartleby2718 commented on .env 2.travis
> +# Dev settings
Is this file supposed to be committed?

2020-11-12 01:56 UTC, Bartleby2718 commented on LICENSE 2
> +                    GNU GENERAL PUBLIC LICENSE
Is this file supposed to be committed?

2020-11-12 01:56 UTC, Bartleby2718 commented on pull_request_template 2.md
> +# What I did
Is this file supposed to be committed?

2020-11-12 01:56 UTC, Bartleby2718 commented on tcf_website/static/about/history/history 2.css
> +/*
Also looks like a duplicate

2020-11-13 04:24 UTC, closed without merging