Add Joe Kerrigan to about page
thecourseforum/theCourseForum2 pull request #363
Opened 2021-02-01 02:06 UTC by joek13

## Status
- Done

## GitHub Issues addressed (`#IssueNumber`)
- N/A

## What I did
- Added my self-portrait to static images
- Added self to about page

## Screenshots
- Before
![image](https://user-images.githubusercontent.com/2716970/106406674-0c12b280-6408-11eb-891f-2586ec07f5e6.png)
- After
![image](https://user-images.githubusercontent.com/2716970/106406686-12089380-6408-11eb-9f73-690d23c64dbe.png)
*(Wow! So handsome!)*
## Tests
- Navigate to the "about" page
- Scroll to the engineering team
- Feast your eyes

## Questions/Discussions/Notes
- N/A

## Merging the PR
- Who should merge this PR?
  - [x] I will merge it myself
  - [ ] The last reviewer to approve can merge it
    - Should the commit history be preserved in the base branch, or is it okay to combine all of them into a single commit ("squash-merge")?
    - [x] preserve the history (single commit)
    - [ ] squash-merge

2021-02-01 02:46 UTC, alex-shen1 approved these changes
Looks good to me! Also thanks for refactoring the JSON as a whole; not sure why it was like that before lol

2021-02-01 02:58 UTC, alex-shen1 requested changes
Scratch that - the pictures should be 800x800 (for file loading speed purposes)

2021-02-01 03:10 UTC, joek13 commented
> Scratch that - the pictures should be 800x800 (for file loading speed purposes)

Nice catch. I've resized it using ImageMagick—should be 800x800 now.

2021-02-02 18:27 UTC, alex-shen1 approved these changes

2021-02-02 18:27 UTC, merged