Blog
thecourseforum/theCourseForum2 pull request #451
Opened 2021-03-21 01:17 UTC by j-alicia-long

## Status
- In progress

## GitHub Issues addressed
- This PR closes #270 (Team Blog)

## What I did
- Created basic blog pipeline using [django-markdownx](https://github.com/neutronX/django-markdownx) 
- Created basic blog layout
- WIP

## Screenshots
- Current WIP:
![image](https://user-images.githubusercontent.com/4724192/111890634-a67f8300-89c1-11eb-89b0-d2519c36cf66.png)

## Tests
- Any unit/interation test recommendations?

## Questions/Discussions/Notes
- Suggestions are welcome

## Merging the PR
- Who should merge this PR?
  - [x] I will merge it myself
  - [ ] The last reviewer to approve can merge it
- Should the commit history be preserved in the base branch, or is it okay to combine all of them into a single commit ("squash-merge")?
  - [x] preserve the history
  - [ ] squash-merge

2021-03-21 01:27 UTC, j-alicia-long commented
^This is what happens when we don't run precommit :'(

2023-02-04 19:13 UTC, jackliu612 requested changes
I don't see any major issues though some minor comments that should be addressed. Some thoughts for the blog in general, should we make an upvote system like with reviews? Also what about comments or search by author/author profiles. I know these might be future ideas but just wanted to put it out there.

2023-02-04 19:13 UTC, jackliu612 commented on tcf_website/models/models.py
> +    author = models.CharField(max_length=50)
Is it possible to link the author up with a user model instead of a char field? Might make management easier in the future

2023-02-04 19:13 UTC, jackliu612 commented on tcf_website/templates/blog/blog.html
> +<!-- {% comment %} <div class="container">
What are these comments? (also adsense below) Either delete or put in

2023-02-04 19:13 UTC, jackliu612 commented on tcf_website/templates/blog/post.html
> +<!-- {% comment %} <div class="container">
ditto previous comment

2023-02-04 19:13 UTC, jackliu612 commented on tcf_website/urls.py
> +    # GOOGLE ADS
Is this a relic of adding google ads from long ago? Is this still necessary

2023-04-30 18:10 UTC, alex-shen1 requested changes
UI pls

2024-04-07 19:21 UTC, wkaisertexas commented
I do not think we are going to continue with this path for the blog. Is it okay if I close this out? @barrett-ruth

2024-04-07 19:21 UTC, closed without merging