Added Message for Subdepartments without Courses
thecourseforum/theCourseForum2 pull request #469
Opened 2021-04-02 19:34 UTC by borjainglefernandez

## Status

- Done

## GitHub Issues addressed

- This PR closes #468 

## What I did

- Added message for when the subdepartment has no courses taught this semester
- Added message for when subdepartment has no courses taught in general
- Added subdepartment name even when no courses are taught for clarity

## Screenshots

- Before
![Screenshot 2021-04-02 at 3 31 01 PM](https://user-images.githubusercontent.com/65180311/113447732-72945c80-93c8-11eb-804d-c4b5a72ce364.png)
![image](https://user-images.githubusercontent.com/65180311/113447697-63adaa00-93c8-11eb-8865-97c073391fef.png)

- After
![image](https://user-images.githubusercontent.com/65180311/113447657-4bd62600-93c8-11eb-9fa3-5876cde6b3f3.png)
![image](https://user-images.githubusercontent.com/65180311/113447662-4e388000-93c8-11eb-801b-a6dabbcb7e30.png)

## Tests

- Go to subdepartments in which there are courses taught but not this semester and verify that the correct message appears. Go to subdepartments in which there are no courses taught in general and verify that the correct message appears. Go to subdepartments in which there are courses taught and verify message does not appear.

## Questions/Discussions/Notes

- I autoformatted the entire file using PyCharm so if there are any formatting issues lmk
- Didn't add messages to the Last 5 years tab (should we?)
- Message could be improved idk 

## Merging the PR

- Who should merge this PR?
  - [] I will merge it myself
  - [] The last reviewer to approve can merge it
- Should the commit history be preserved in the base branch, or is it okay to combine all of them into a single commit ("squash-merge")?
  - [] preserve the history
  - [] squash-merge

## Add your changes to "Next Update" on the [release history page](https://github.com/thecourseforum/theCourseForum2/wiki/Release-History) once your PR gets merged!

2021-04-30 05:09 UTC, quyenxhuynh commented
Kind of an edge case for sure but under miscellaneous/miscellaneous it's repeated for each subdepartment - not sure if we want it to take up that much space for each one especially since there's so many?
<img width="1440" alt="Screen Shot 2021-04-30 at 1 06 28 AM" src="https://user-images.githubusercontent.com/44627898/116651150-7fb55480-a950-11eb-9b42-f3ee7d957567.png">
Similarly it's kind of weird to have it take up a lot of space there and not any under Last 5 Years at all? I do think it'd be beneficial to have _something_. 
<img width="1440" alt="Screen Shot 2021-04-30 at 1 06 56 AM" src="https://user-images.githubusercontent.com/44627898/116651241-c4d98680-a950-11eb-8e92-ca33a1f0cfcd.png">

2021-05-02 01:41 UTC, alex-shen1 requested changes

2021-05-02 01:41 UTC, alex-shen1 commented on tcf_website/templates/department/department.html
> +                    Looks like this subdepartment has no courses that are taught as of now. <i
I'd change this to "hasn't been offering courses for a while" or something like that because IMO "as of now" is a little vague.

2021-05-02 01:41 UTC, alex-shen1 commented on tcf_website/templates/department/department.html
> +                        class="far fa-frown-open fa-fw"></i>
Super pedantic, but can you move the `<i` opening to this tag from the line above to this one? lol

2021-05-02 01:43 UTC, alex-shen1 commented
RE: @quyenxhuynh's feedback, I think it's probably fine to have the "no courses taught" card repeat, because each subdepartment is distinct. Also, agree that the "Last 5 years" filter should also have the no information card.

2021-05-02 01:44 UTC, alex-shen1 commented on tcf_website/templates/department/department.html
> +                        class="far fa-frown-open fa-fw"></i>
And the other <i> tag... super weird that they'd choose to do it like that, probably the autoformatter not recognizing that it's the same tag.

2021-05-10 02:22 UTC, borjainglefernandez commented
@alex-shen1 I keep trying to add the message to the Last 5 Years portion but I can't seem to find where to add it. I tried putting some sort of logic in the loadmorecourses function but that seems to not to work and make the page load forever.

2021-09-22 21:06 UTC, closed without merging