Added Myself to About
thecourseforum/theCourseForum2 pull request #703
Opened 2023-10-16 03:28 UTC by arthurwu1227

## GitHub Issues addressed

- This PR closes

## What I did

- Added Arthur Wu to About page

## Screenshots

-Before
<img width="1066" alt="Screenshot 2023-10-15 at 11 27 47 PM" src="https://github.com/thecourseforum/theCourseForum2/assets/64984099/cf6cf87d-d1d7-4228-9a67-51c84139dfaa">

- After
<img width="1060" alt="Screenshot 2023-10-15 at 11 27 59 PM" src="https://github.com/thecourseforum/theCourseForum2/assets/64984099/59c79f5f-05d0-414d-bede-2c69d5906be7">

2023-10-16 04:36 UTC, Ann924 requested changes
Hey Arthur, the changes look good! However, your image dimensions are slightly off (768 x 800). Could you please edit the image or select another photo to get 800px x 800px?

2023-10-16 15:29 UTC, arthurwu1227 commented
Hi Ann,

I have resized the image to be 800px x 800px.

2023-10-17 14:18 UTC, Ann924 submitted a review, later dismissed
Looks great! You can go ahead and merge when you're ready.

2023-10-18 04:32 UTC, Ann924 approved these changes

2023-10-18 04:32 UTC, merged